<?php
require_once('Zend/Controller/Action.php');
require_once("views/MySmarty.class.php");
require_once("models/Init.class.php");
require_once("models/Manage.class.php");
require_once("models/Util.class.php");
require_once("models/GetMaster.class.php");
require_once("models/GetMeta.class.php");
require_once("models/DBMaster.class.php");
require_once("models/LogMaster.class.php");
?>